name: Website update

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - uses: actions/checkout@master
      # Node install & build
      - name: Node install & build
        uses: actions/setup-node@v1
        with:
          node-version: '16'
      - run: npm install
      - run: npm run build
      # FTP deployment
      - name: Deploy to FTP
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ${{ secrets.FTP_SERVER_URL }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp
          port: 21
          local-dir: "dist/poke-tcgsky/"
          server-dir: "poketcgsky/"
